# Generated by Django 4.1.1 on 2022-09-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_img_post_im'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='im',
            new_name='img',
        ),
    ]
