# Generated by Django 4.1.1 on 2022-09-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_im_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TimeField(max_length=1000, null=True),
        ),
    ]
