# Generated by Django 4.1.1 on 2022-09-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_created_at_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='author',
        ),
    ]
