# Generated by Django 4.1.1 on 2022-09-23 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 22, 34, 38, 126279, tzinfo=datetime.timezone.utc)),
        ),
    ]
